// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WorkerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerRequest) Reset()         { *m = WorkerRequest{} }
func (m *WorkerRequest) String() string { return proto.CompactTextString(m) }
func (*WorkerRequest) ProtoMessage()    {}
func (*WorkerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *WorkerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerRequest.Unmarshal(m, b)
}
func (m *WorkerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerRequest.Marshal(b, m, deterministic)
}
func (m *WorkerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerRequest.Merge(m, src)
}
func (m *WorkerRequest) XXX_Size() int {
	return xxx_messageInfo_WorkerRequest.Size(m)
}
func (m *WorkerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerRequest proto.InternalMessageInfo

type LogPart struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	JobId                uint64   `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Number               int64    `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Uuid                 string   `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Final                bool     `protobuf:"varint,6,opt,name=final,proto3" json:"final,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogPart) Reset()         { *m = LogPart{} }
func (m *LogPart) String() string { return proto.CompactTextString(m) }
func (*LogPart) ProtoMessage()    {}
func (*LogPart) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *LogPart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogPart.Unmarshal(m, b)
}
func (m *LogPart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogPart.Marshal(b, m, deterministic)
}
func (m *LogPart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogPart.Merge(m, src)
}
func (m *LogPart) XXX_Size() int {
	return xxx_messageInfo_LogPart.Size(m)
}
func (m *LogPart) XXX_DiscardUnknown() {
	xxx_messageInfo_LogPart.DiscardUnknown(m)
}

var xxx_messageInfo_LogPart proto.InternalMessageInfo

func (m *LogPart) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogPart) GetJobId() uint64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *LogPart) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *LogPart) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *LogPart) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *LogPart) GetFinal() bool {
	if m != nil {
		return m.Final
	}
	return false
}

type JobStatus struct {
	JobId                uint64   `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobStatus) Reset()         { *m = JobStatus{} }
func (m *JobStatus) String() string { return proto.CompactTextString(m) }
func (*JobStatus) ProtoMessage()    {}
func (*JobStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *JobStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStatus.Unmarshal(m, b)
}
func (m *JobStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStatus.Marshal(b, m, deterministic)
}
func (m *JobStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStatus.Merge(m, src)
}
func (m *JobStatus) XXX_Size() int {
	return xxx_messageInfo_JobStatus.Size(m)
}
func (m *JobStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStatus.DiscardUnknown(m)
}

var xxx_messageInfo_JobStatus proto.InternalMessageInfo

func (m *JobStatus) GetJobId() uint64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *JobStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*WorkerRequest)(nil), "agent.WorkerRequest")
	proto.RegisterType((*LogPart)(nil), "agent.LogPart")
	proto.RegisterType((*JobStatus)(nil), "agent.JobStatus")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x6b, 0x1a, 0xbb, 0xe4, 0xf8, 0x2b, 0xab, 0x54, 0x16, 0x53, 0xe4, 0x29, 0x53, 0x07,
	0x60, 0x40, 0x6c, 0x4c, 0x15, 0x88, 0x01, 0x99, 0x81, 0x11, 0xd9, 0xc4, 0x54, 0x29, 0xd4, 0x06,
	0xe7, 0x2c, 0xbe, 0x06, 0x1f, 0x19, 0xc5, 0x71, 0xa1, 0x48, 0x6c, 0xf7, 0x3b, 0x3d, 0xdf, 0xf3,
	0x7b, 0xb0, 0xa7, 0x97, 0xd6, 0xe1, 0xfc, 0x3d, 0x78, 0xf4, 0x9c, 0x26, 0x90, 0x47, 0x70, 0xf0,
	0xe8, 0xc3, 0xab, 0x0d, 0xca, 0x7e, 0x44, 0xdb, 0xa1, 0xfc, 0x22, 0x30, 0xb9, 0xf3, 0xcb, 0x7b,
	0x1d, 0x90, 0x73, 0x28, 0x9c, 0x5e, 0x5b, 0x41, 0x2a, 0x52, 0x97, 0x2a, 0xcd, 0xfc, 0x04, 0xd8,
	0xca, 0x9b, 0xa7, 0xb6, 0x11, 0x3b, 0x15, 0xa9, 0x0b, 0x45, 0x57, 0xde, 0xdc, 0x34, 0x5c, 0xc0,
	0xe4, 0xd9, 0x3b, 0xb4, 0x0e, 0xc5, 0x38, 0xa9, 0x37, 0xc8, 0x67, 0xc0, 0x5c, 0x5c, 0x1b, 0x1b,
	0x44, 0x51, 0x91, 0x7a, 0xac, 0x32, 0xf5, 0xc7, 0x63, 0x6c, 0x1b, 0x41, 0x87, 0xe3, 0xfd, 0xcc,
	0xa7, 0x40, 0x5f, 0x5a, 0xa7, 0xdf, 0x04, 0xab, 0x48, 0xbd, 0xab, 0x06, 0x90, 0x57, 0x50, 0xde,
	0x7a, 0xf3, 0x80, 0x1a, 0x63, 0xb7, 0xe5, 0x4f, 0xb6, 0xfd, 0x67, 0xc0, 0xba, 0x24, 0x48, 0xdf,
	0x2a, 0x55, 0xa6, 0xb3, 0x4f, 0xa0, 0xd7, 0x7d, 0x50, 0x7e, 0x01, 0xb0, 0xb0, 0xb8, 0x49, 0x36,
	0x9d, 0x0f, 0x5d, 0xfc, 0xc9, 0x7e, 0x7a, 0x98, 0xb7, 0x59, 0x25, 0x47, 0xfc, 0x12, 0xf6, 0x17,
	0x16, 0x7f, 0xdd, 0xff, 0x7f, 0x77, 0x9c, 0xb7, 0x3f, 0x3a, 0x39, 0x32, 0x2c, 0xd5, 0x7c, 0xfe,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x58, 0xc8, 0x59, 0x77, 0x75, 0x01, 0x00, 0x00,
}
