// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WorkerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerRequest) Reset()         { *m = WorkerRequest{} }
func (m *WorkerRequest) String() string { return proto.CompactTextString(m) }
func (*WorkerRequest) ProtoMessage()    {}
func (*WorkerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *WorkerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerRequest.Unmarshal(m, b)
}
func (m *WorkerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerRequest.Marshal(b, m, deterministic)
}
func (m *WorkerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerRequest.Merge(m, src)
}
func (m *WorkerRequest) XXX_Size() int {
	return xxx_messageInfo_WorkerRequest.Size(m)
}
func (m *WorkerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerRequest proto.InternalMessageInfo

type RunJobRequest struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	LogTimeoutS          int64    `protobuf:"varint,2,opt,name=log_timeout_s,json=logTimeoutS,proto3" json:"log_timeout_s,omitempty"`
	HardTimeoutS         int64    `protobuf:"varint,3,opt,name=hard_timeout_s,json=hardTimeoutS,proto3" json:"hard_timeout_s,omitempty"`
	Maxloglength         int64    `protobuf:"varint,4,opt,name=maxloglength,proto3" json:"maxloglength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunJobRequest) Reset()         { *m = RunJobRequest{} }
func (m *RunJobRequest) String() string { return proto.CompactTextString(m) }
func (*RunJobRequest) ProtoMessage()    {}
func (*RunJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *RunJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunJobRequest.Unmarshal(m, b)
}
func (m *RunJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunJobRequest.Marshal(b, m, deterministic)
}
func (m *RunJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunJobRequest.Merge(m, src)
}
func (m *RunJobRequest) XXX_Size() int {
	return xxx_messageInfo_RunJobRequest.Size(m)
}
func (m *RunJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunJobRequest proto.InternalMessageInfo

func (m *RunJobRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *RunJobRequest) GetLogTimeoutS() int64 {
	if m != nil {
		return m.LogTimeoutS
	}
	return 0
}

func (m *RunJobRequest) GetHardTimeoutS() int64 {
	if m != nil {
		return m.HardTimeoutS
	}
	return 0
}

func (m *RunJobRequest) GetMaxloglength() int64 {
	if m != nil {
		return m.Maxloglength
	}
	return 0
}

type RunJobResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunJobResponse) Reset()         { *m = RunJobResponse{} }
func (m *RunJobResponse) String() string { return proto.CompactTextString(m) }
func (*RunJobResponse) ProtoMessage()    {}
func (*RunJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *RunJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunJobResponse.Unmarshal(m, b)
}
func (m *RunJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunJobResponse.Marshal(b, m, deterministic)
}
func (m *RunJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunJobResponse.Merge(m, src)
}
func (m *RunJobResponse) XXX_Size() int {
	return xxx_messageInfo_RunJobResponse.Size(m)
}
func (m *RunJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunJobResponse proto.InternalMessageInfo

func (m *RunJobResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type LogPart struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	JobId                uint64   `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Number               int64    `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Uuid                 string   `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Final                bool     `protobuf:"varint,6,opt,name=final,proto3" json:"final,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogPart) Reset()         { *m = LogPart{} }
func (m *LogPart) String() string { return proto.CompactTextString(m) }
func (*LogPart) ProtoMessage()    {}
func (*LogPart) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *LogPart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogPart.Unmarshal(m, b)
}
func (m *LogPart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogPart.Marshal(b, m, deterministic)
}
func (m *LogPart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogPart.Merge(m, src)
}
func (m *LogPart) XXX_Size() int {
	return xxx_messageInfo_LogPart.Size(m)
}
func (m *LogPart) XXX_DiscardUnknown() {
	xxx_messageInfo_LogPart.DiscardUnknown(m)
}

var xxx_messageInfo_LogPart proto.InternalMessageInfo

func (m *LogPart) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogPart) GetJobId() uint64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *LogPart) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *LogPart) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *LogPart) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *LogPart) GetFinal() bool {
	if m != nil {
		return m.Final
	}
	return false
}

type JobStatus struct {
	JobId                uint64   `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobStatus) Reset()         { *m = JobStatus{} }
func (m *JobStatus) String() string { return proto.CompactTextString(m) }
func (*JobStatus) ProtoMessage()    {}
func (*JobStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4}
}

func (m *JobStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStatus.Unmarshal(m, b)
}
func (m *JobStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStatus.Marshal(b, m, deterministic)
}
func (m *JobStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStatus.Merge(m, src)
}
func (m *JobStatus) XXX_Size() int {
	return xxx_messageInfo_JobStatus.Size(m)
}
func (m *JobStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStatus.DiscardUnknown(m)
}

var xxx_messageInfo_JobStatus proto.InternalMessageInfo

func (m *JobStatus) GetJobId() uint64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *JobStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*WorkerRequest)(nil), "agent.WorkerRequest")
	proto.RegisterType((*RunJobRequest)(nil), "agent.RunJobRequest")
	proto.RegisterType((*RunJobResponse)(nil), "agent.RunJobResponse")
	proto.RegisterType((*LogPart)(nil), "agent.LogPart")
	proto.RegisterType((*JobStatus)(nil), "agent.JobStatus")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xb1, 0x6e, 0xea, 0x30,
	0x18, 0x85, 0x09, 0x90, 0x70, 0xf3, 0x03, 0xb9, 0x57, 0x16, 0xa0, 0x88, 0x09, 0x59, 0x77, 0x60,
	0x62, 0x68, 0x2b, 0xb5, 0xea, 0xd6, 0x09, 0x15, 0x75, 0xa8, 0x42, 0xa5, 0x8e, 0x28, 0x69, 0xdc,
	0x10, 0x48, 0xfc, 0xd3, 0xc4, 0x96, 0xfa, 0x18, 0x1d, 0xfa, 0x20, 0x7d, 0xc4, 0x2a, 0xb6, 0x93,
	0x02, 0xea, 0xe6, 0x73, 0x74, 0x6c, 0x7f, 0xbf, 0x8f, 0xa1, 0x1f, 0x26, 0x8c, 0x8b, 0xc5, 0xa1,
	0x40, 0x81, 0xc4, 0x56, 0x82, 0xfe, 0x85, 0xe1, 0x33, 0x16, 0x7b, 0x56, 0x04, 0xec, 0x4d, 0xb2,
	0x52, 0xd0, 0x4f, 0x0b, 0x86, 0x81, 0xe4, 0x2b, 0x8c, 0x8c, 0x43, 0xc6, 0xe0, 0xec, 0x30, 0xda,
	0xa4, 0xb1, 0x6f, 0xcd, 0xac, 0xb9, 0x1b, 0xd8, 0x3b, 0x8c, 0xee, 0x63, 0x42, 0x61, 0x98, 0x61,
	0xb2, 0x11, 0x69, 0xce, 0x50, 0x8a, 0x4d, 0xe9, 0xb7, 0x67, 0xd6, 0xbc, 0x13, 0xf4, 0x33, 0x4c,
	0x9e, 0xb4, 0xb7, 0x26, 0xff, 0xc1, 0xdb, 0x86, 0x45, 0x7c, 0x14, 0xea, 0xa8, 0xd0, 0xa0, 0x72,
	0x9b, 0x14, 0x85, 0x41, 0x1e, 0xbe, 0x67, 0x98, 0x64, 0x8c, 0x27, 0x62, 0xeb, 0x77, 0x75, 0xe6,
	0xd8, 0xa3, 0x33, 0xf0, 0x6a, 0xaa, 0xf2, 0x80, 0xbc, 0x64, 0xc4, 0x83, 0x36, 0xee, 0x15, 0xd2,
	0x9f, 0xa0, 0x8d, 0x7b, 0xfa, 0x61, 0x41, 0xef, 0x01, 0x93, 0xc7, 0xb0, 0x10, 0x84, 0x40, 0x97,
	0x87, 0x39, 0x33, 0xc0, 0x6a, 0x7d, 0x34, 0x46, 0x05, 0xda, 0xad, 0xc7, 0xf0, 0xa1, 0xf7, 0x82,
	0x5c, 0x30, 0x2e, 0x14, 0x9b, 0x1b, 0xd4, 0x92, 0x4c, 0xc0, 0xe1, 0x32, 0x8f, 0x58, 0x61, 0x80,
	0x8c, 0xaa, 0x0e, 0x97, 0x32, 0x8d, 0x7d, 0x5b, 0x1f, 0x5e, 0xad, 0xc9, 0x08, 0xec, 0xd7, 0x94,
	0x87, 0x99, 0xef, 0x28, 0x1e, 0x2d, 0xe8, 0x2d, 0xb8, 0x2b, 0x8c, 0xd6, 0x22, 0x14, 0xb2, 0x3c,
	0x7b, 0xc6, 0xe6, 0xfe, 0x09, 0x38, 0xa5, 0x0a, 0x28, 0x2c, 0x37, 0x30, 0xea, 0xe2, 0xcb, 0x02,
	0xfb, 0xae, 0xaa, 0x88, 0x5c, 0x01, 0x2c, 0x99, 0xa8, 0x47, 0x1b, 0x2d, 0x74, 0x8b, 0x27, 0xad,
	0x4d, 0x3d, 0xe3, 0x9a, 0x14, 0x6d, 0x91, 0x1b, 0x18, 0x2c, 0x99, 0xf8, 0xb9, 0xfe, 0xf7, 0x7d,
	0xff, 0x8c, 0xdb, 0xe4, 0x68, 0x8b, 0x5c, 0x83, 0xa3, 0x9f, 0xba, 0xd9, 0x73, 0xf2, 0x1f, 0xa6,
	0xe3, 0x33, 0x57, 0xf7, 0x41, 0x5b, 0x91, 0xa3, 0x7e, 0xd6, 0xe5, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x95, 0x9f, 0xe6, 0x65, 0x68, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	GetLogPart(ctx context.Context, in *WorkerRequest, opts ...grpc.CallOption) (*LogPart, error)
	GetJobStatus(ctx context.Context, in *WorkerRequest, opts ...grpc.CallOption) (*JobStatus, error)
	RunJob(ctx context.Context, in *RunJobRequest, opts ...grpc.CallOption) (*RunJobResponse, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) GetLogPart(ctx context.Context, in *WorkerRequest, opts ...grpc.CallOption) (*LogPart, error) {
	out := new(LogPart)
	err := c.cc.Invoke(ctx, "/agent.Agent/GetLogPart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetJobStatus(ctx context.Context, in *WorkerRequest, opts ...grpc.CallOption) (*JobStatus, error) {
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, "/agent.Agent/GetJobStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) RunJob(ctx context.Context, in *RunJobRequest, opts ...grpc.CallOption) (*RunJobResponse, error) {
	out := new(RunJobResponse)
	err := c.cc.Invoke(ctx, "/agent.Agent/RunJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	GetLogPart(context.Context, *WorkerRequest) (*LogPart, error)
	GetJobStatus(context.Context, *WorkerRequest) (*JobStatus, error)
	RunJob(context.Context, *RunJobRequest) (*RunJobResponse, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_GetLogPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetLogPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/GetLogPart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetLogPart(ctx, req.(*WorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/GetJobStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetJobStatus(ctx, req.(*WorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_RunJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RunJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/RunJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RunJob(ctx, req.(*RunJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLogPart",
			Handler:    _Agent_GetLogPart_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _Agent_GetJobStatus_Handler,
		},
		{
			MethodName: "RunJob",
			Handler:    _Agent_RunJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
